[package]
name = "watchfiles_rust_notify"
version = "0.14.1"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.4"
notify = "=5.0.0-pre.15"
pyo3 = {version = "0.16.4", features = ["extension-module", "abi3-py37"]}

[lib]
name = "_rust_notify"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "watchfiles._rust_notify"
